import sys
import os
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from config import PROCESSED_DIR

st.set_page_config(page_title="PriceIQ Competitor Intel", layout="wide")

@st.cache_data(ttl=3600)
def load_data():
    fs_path = PROCESSED_DIR / "feature_store.csv"
    if not fs_path.exists():
        return None
    return pd.read_csv(fs_path)

@st.cache_data(ttl=3600)
def get_mock_sentiment_data(competitors):
    # For a real app, this would load from sentiment_cache.pkl generated by SentimentAnalyzer
    np.random.seed(42)
    scores = {}
    radar_data = {}
    reviews_data = []
    
    aspects = ["Quality", "Delivery", "Price", "Service"]
    
    for comp in competitors:
        scores[comp] = np.random.uniform(0.1, 0.9)
        radar_data[comp] = {a: np.random.uniform(0.2, 0.9) for a in aspects}
        
        for _ in range(20):
            sent = np.random.choice(["POSITIVE", "NEGATIVE"], p=[0.6, 0.4])
            reviews_data.append({
                "competitor": comp,
                "Text": f"Sample review for {comp}. " + ("Great product!" if sent == "POSITIVE" else "Terrible experience, would not recommend."),
                "predicted_sentiment": sent,
                "confidence": np.random.uniform(0.7, 0.99)
            })
            
    return scores, radar_data, pd.DataFrame(reviews_data)

def main():
    st.title("🕵️ Competitor Intelligence")
    
    fs_df = load_data()
    if fs_df is None:
        st.warning("Data not found. Run ETL pipeline first.")
        return
        
    # Get competitors from synthetic data setup
    latest_df = fs_df.sort_values('date').groupby('product_id').last().reset_index()
    latest_df = latest_df.drop(columns=['competitor_price']).rename(columns={'units_sold': 'base_demand', 'price_charged': 'current_price', 'avg_competitor_price': 'competitor_price', 'current_stock': 'stock_level'})
    # In our synthetic data, competitors are generic (Competitor 1, 2, 3) or just average. Let's mock a few names for realism
    competitors = ["Amazon Basics", "Brand X", "Value Plus", "Premium Co", "FastShip Inc"]
    
    scores, radar_data, reviews_df = get_mock_sentiment_data(competitors)
    
    st.subheader("Section 1 — Competitor Weakness Scores")
    st.markdown("Higher score = more negative customer sentiment = pricing opportunity for you")
    
    score_df = pd.DataFrame([{"Competitor": k, "Weakness Score": v} for k, v in scores.items()])
    score_df = score_df.sort_values("Weakness Score", ascending=True)
    
    fig_bar = px.bar(score_df, x="Weakness Score", y="Competitor", orientation='h', color="Weakness Score", color_continuous_scale="RdYlGn_r")
    st.plotly_chart(fig_bar, use_container_width=True)
    
    st.markdown("---")
    
    st.subheader("Section 2 — Aspect Sentiment Radar")
    selected_comp = st.selectbox("Select Competitor", competitors)
    
    comp_radar = radar_data[selected_comp]
    categories = list(comp_radar.keys())
    values = list(comp_radar.values())
    
    # Close the radar loop
    categories.append(categories[0])
    values.append(values[0])
    
    fig_radar = go.Figure()
    fig_radar.add_trace(go.Scatterpolar(
        r=values,
        theta=categories,
        fill='toself',
        fillcolor='rgba(0, 128, 0, 0.3)',
        line_color='green',
        name=selected_comp
    ))
    fig_radar.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
        showlegend=False,
        title=f"Customer Sentiment Breakdown — {selected_comp}"
    )
    st.plotly_chart(fig_radar, use_container_width=True)
    
    st.markdown("---")
    
    st.subheader("Section 3 — Review Sample Browser")
    comp_reviews = reviews_df[reviews_df['competitor'] == selected_comp].copy()
    comp_reviews['Text'] = comp_reviews['Text'].str.slice(0, 100) + "..."
    
    def color_sentiment(val):
        color = 'green' if val == 'POSITIVE' else 'red'
        return f'color: {color}; font-weight: bold'
        
    styled_reviews = comp_reviews[['Text', 'predicted_sentiment', 'confidence']].style.map(color_sentiment, subset=['predicted_sentiment']).format({'confidence': '{:.2f}'})
    st.dataframe(styled_reviews, use_container_width=True, height=400)
    
    st.markdown("---")
    
    st.subheader("Section 4 — Price Gap Analysis")
    if 'category' in latest_df.columns:
        cat_price = latest_df.groupby('category').agg({
            'current_price': 'mean',
            'competitor_price': 'mean'
        }).reset_index()
        
        fig_gap = go.Figure()
        fig_gap.add_trace(go.Bar(x=cat_price['category'], y=cat_price['current_price'], name='Our Price'))
        fig_gap.add_trace(go.Bar(x=cat_price['category'], y=cat_price['competitor_price'], name='Market Average'))
        
        # Highlight gaps
        for i, row in cat_price.iterrows():
            if row['current_price'] > row['competitor_price'] * 1.10:
                fig_gap.add_annotation(
                    x=row['category'],
                    y=row['current_price'],
                    text=">10% Gap",
                    showarrow=True,
                    arrowhead=1,
                    bordercolor="red"
                )
                
        fig_gap.update_layout(barmode='group', title="Price Gap by Category")
        st.plotly_chart(fig_gap, use_container_width=True)
        
    st.markdown("---")
    
    st.subheader("Section 5 — Strategic Insights")
    top_3_weak = score_df.sort_values("Weakness Score", ascending=False).head(3)['Competitor'].tolist()
    
    for comp in top_3_weak:
        # Find weakest aspect
        radar = radar_data[comp]
        weakest_aspect = min(radar, key=radar.get)
        weakest_val = radar[weakest_aspect]
        
        strength_aspect = max(radar, key=radar.get)
        
        insight = f"Competitor **{comp}** shows weakness in **{weakest_aspect.lower()}** (sentiment ratio: {weakest_val:.2f}). With their weakness score of {scores[comp]:.2f}, consider positioning on **{strength_aspect.lower()}** at a **premium** market price."
        st.info(insight)

if __name__ == "__main__":
    main()
